language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.3
      env: REQUIRED_PACKAGE="symfony/symfony=v2.5.12"
    - php: 5.3
      env: REQUIRED_PACKAGE="symfony/symfony=v2.6.11"
    - php: 5.3
      env: REQUIRED_PACKAGE="symfony/symfony=^2.7"
    - php: 5.3
      env: REQUIRED_PACKAGE="symfony/form=v2.6.11"
    - php: 5.3
      env: REQUIRED_PACKAGE="symfony/form=^2.7"

before_install:
  - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - echo 'extension = "mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - if [ "$REQUIRED_PACKAGE" != "" ]; then composer require --dev --no-update $REQUIRED_PACKAGE; fi

install: composer update $COMPOSER_FLAGS --prefer-source

script: ./vendor/bin/phpunit
